# Generated by Django 6.1.1 on 2026-09-26 02:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(help_text='When students can start taking the exam')),
                ('end_time', models.DateTimeField(help_text='Last time a student can start the exam')),
                ('duration_minutes', models.IntegerField(help_text='How long students have to complete the exam once started', validators=[django.core.validators.MinValueValidator(1)])),
                ('question_count', models.IntegerField(help_text='Number of questions to draw from the bank per student', validators=[django.core.validators.MinValueValidator(1)])),
                ('marks_per_question', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_marks_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Marks deducted for wrong answers (if negative_marking is enabled)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('shuffle_questions', models.BooleanField(default=True, help_text='Randomize question order per student')),
                ('shuffle_options', models.BooleanField(default=True, help_text='Randomize option order per student')),
                ('proctoring_mode', models.CharField(choices=[('off', 'Off'), ('basic', 'Basic'), ('strict', 'Strict')], default='basic', max_length=10)),
                ('is_published', models.BooleanField(default=False, help_text='Students can only see/join published exams (SRS.md FR-12)')),
                ('results_published', models.BooleanField(default=False, help_text='Students can only view results after this is set (SRS.md FR-28)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mcq_single', 'Single Correct MCQ'), ('mcq_multi', 'Multi Correct MCQ'), ('short_answer', 'Short Answer')], max_length=20)),
                ('text', models.TextField(help_text='Question text')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('topic', models.CharField(blank=True, help_text='Topic/tag for filtering', max_length=200)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order in the question pool (before per-student randomization)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.question')),
            ],
            options={
                'db_table': 'exam_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Default display order (will be randomized per student)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
            options={
                'db_table': 'question_options',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'is_published'], name='exams_course__88a174_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time', 'end_time'], name='exams_start_t_d9bb07_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['course', 'type'], name='questions_course__ca32d6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='questions_difficu_8150ad_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic'], name='questions_topic_98a2c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('exam', 'question')},
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'order'], name='question_op_questio_3964be_idx'),
        ),
    ]
