# Generated by Django 6.1.1 on 2026-09-26 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(help_text='Server-computed end time = started_at + exam.duration_minutes (source of truth)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted'), ('voided', 'Voided')], default='in_progress', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Total score after grading', max_digits=6, null=True)),
                ('integrity_score', models.DecimalField(blank=True, decimal_places=2, help_text='Proctoring integrity score (Phase 5)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_ids', models.JSONField(blank=True, default=list, help_text='List of selected option IDs for MCQ questions')),
                ('text_answer', models.TextField(blank=True, help_text='Text answer for short-answer questions')),
                ('is_marked_for_review', models.BooleanField(default=False, help_text='Student marked this question for review (SRS.md FR-17)')),
                ('is_visited', models.BooleanField(default=False, help_text='Student has visited this question')),
                ('is_correct', models.BooleanField(blank=True, help_text='Auto-graded result for objective questions', null=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded after grading', max_digits=5, null=True)),
                ('grading_feedback', models.TextField(blank=True, help_text='Optional feedback from grader')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.attempt')),
                ('graded_by', models.ForeignKey(blank=True, help_text='Faculty who graded this answer (for subjective questions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
            options={
                'db_table': 'attempt_answers',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Randomized order for this student')),
                ('shuffled_option_order', models.JSONField(default=list, help_text='Randomized option IDs order for this student (for MCQ questions)')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='exams.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
            options={
                'db_table': 'attempt_questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'status'], name='attempts_student_e45216_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam', 'status'], name='attempts_exam_id_e4b38a_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['end_time', 'status'], name='attempts_end_tim_20f08c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('exam', 'student')},
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'question'], name='attempt_ans_attempt_91b708_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='attemptquestion',
            unique_together={('attempt', 'question')},
        ),
    ]
