# Generated by Django 6.1.1 on 2026-09-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_attempt_attemptanswer_attemptquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model_answer',
            field=models.TextField(blank=True, default='', help_text='Reference answer for short-answer questions: shown to graders and used only for AI-assist suggestions (never auto-applied)'),
        ),
    ]
