# Generated by Django 6.1.1 on 2026-09-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_model_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='reference_photo',
            field=models.ImageField(blank=True, help_text='One-time reference still captured at exam start (FR-14)', null=True, upload_to='proctoring/reference/'),
        ),
    ]
