# Generated by Django 6.1.1 on 2026-09-26 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0004_attempt_reference_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('FACE_MISMATCH', 'Face Mismatch'), ('TAB_SWITCH', 'Tab Switch / Window Blur'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('CLIPBOARD_EVENT', 'Copy/Paste Attempted'), ('DEVTOOLS_ATTEMPT', 'Devtools Attempt'), ('LOUD_NOISE', 'Loud Noise')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ImageField(blank=True, help_text='Compressed flagged-moment thumbnail only (NFR-10)', null=True, upload_to='proctoring/%Y/%m/')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Client timestamp, durations, thresholds — never video')),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='exams.attempt')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoring_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
